name: Build and update documentation

# Daily at 0 am
on:
  schedule:
    - cron: '0 0 * * *'

# Branch where translation takes place
env:
  BRANCH: 3.9

jobs:

  # Job to pull, build and push translations from Transifex to the repository
  update:
    if: (github.event_name == 'schedule' && github.repository == 'python/python-docs-pt-br') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH }}
    - uses: actions/setup-python@v2
    - run: sudo apt update
    - run: sudo apt install -y gettext
    - run: make tx-config
    - name: Run make pull
      run: |
        if [[ -n "$TRANSIFEX_APIKEY" ]]; then
            echo -e "[https://www.transifex.com]\n"          \
                "api_hostname = https://api.transifex.com\n" \
                "hostname = https://www.transifex.com\n"     \
                "password = $TRANSIFEX_APIKEY\n"             \
                "username = api"                             \
                > ~/.transifexrc
        fi
        make pull
        git status --short
      env:
          TRANSIFEX_APIKEY: ${{ secrets.TRANSIFEX_APIKEY }}
    - run: make build CPYTHON_PATH=/tmp/cpython/ SPHINXERRORHANDLING=''
    - name: Run make push
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        make push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: appleboy/telegram-action@master
      if: ${{ failure() }}
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        args: "❌ Falha na execução do workflow, job&nbsp;*${{ github.job }}* (ID&nbsp;*${{ github.run_id }}*). [Saiba mais sobre o erro...](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"

  # Job to check spelling of translations
  spellcheck:
    if: (github.event_name == 'schedule' && github.repository == 'python/python-docs-pt-br') || (github.event_name != 'schedule')
    needs: update
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH }}
    - uses: actions/setup-python@v2
    - run: sudo apt update
    - run: sudo apt install -y gettext hunspell hunspell-pt-br
    - name: Run make spell
      run: |
        make spell
        cd .pospell/
        tar -czf ../pospell-out.tar.gz *.txt **/*.txt
    - name: Update artifact spellchecking-output
      uses: actions/upload-artifact@v2
      with:
        name: spellchecking-output
        path: pospell-out.tar.gz

  # Job to merge translation from current BRANCH to older ones
  merge:
    if: (github.event_name == 'schedule' && github.repository == 'python/python-docs-pt-br') || (github.event_name != 'schedule')
    needs: update
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH }}
    - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - uses: actions/setup-python@v2
    - run: sudo apt update
    - run: sudo apt install -y gettext
    - name: Run make push
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        make merge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job to build translated documentation treating warnings as errors
  build-warn-as-err:
    if: (github.event_name == 'schedule' && github.repository == 'python/python-docs-pt-br') || (github.event_name != 'schedule')
    needs: update
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH }}
    - uses: actions/setup-python@v2
    - run: make build CPYTHON_PATH=/tmp/cpython/ 2> >(tee -a build-log.txt >&2)
    - name: Update artifact build-output
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: build-log.txt
    - uses: appleboy/telegram-action@master
      if: ${{ failure() }}
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        args: "❌ Falha na execução do workflow, job&nbsp;*${{ github.job }}* (ID&nbsp;*${{ github.run_id }}*). [Saiba mais sobre o erro...](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
